kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: decice  # Same namespace as the one in the context
  name: decice
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]
