apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: default
spec:
  type: NodePort
  selector:
    run: registry
  ports:
    - name: registry-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
